on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (для контексту)
        uses: actions/checkout@v3

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY_01 }}

      - name: Add server to known_hosts
        run: |
             mkdir -p ~/.ssh
             chmod 700 ~/.ssh
             ssh-keyscan -H -p ${{ secrets.SERVER_SSH_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
             chmod 644 ~/.ssh/known_hosts

      - name: Pull & run update script on server
        run: |
          ssh -p ${{ secrets.SERVER_SSH_PORT }} \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
            "/usr/local/bin/magento_deploy.sh dev /var/www/vbox"
